export const posts = [
  {
    id: 1,
    title: 'The Art of Building Software That Lasts',
    desc: 'Good software is not just about making things work. It is about making thoughtful decisions that remain useful long after the first release.',
    date: '12-01-2026',
    img: 'assets/1.jpg',
    author: 'Daniel Carter',
  },
  {
    id: 2,
    title: 'Why Simplicity Is a Superpower in Software Development',
    desc: 'Complexity is easy to introduce and difficult to remove. Learning when to keep an architecture simple can be one of the most valuable engineering skills.',
    date: '28-01-2026',
    img: 'assets/2.jpg',
    author: 'Ethan Brooks',
  },
  {
    id: 3,
    title: 'Understanding the Difference Between Code and Architecture',
    desc: 'Writing clean code matters, but software architecture determines how that code evolves, communicates, and survives as a project grows.',
    date: '14-02-2026',
    img: 'assets/3.jpg',
    author: 'Marcus Bennett',
  },
  {
    id: 4,
    title: 'What Actually Happens When You Visit a Website',
    desc: 'From DNS and HTTP to servers, databases, and browser rendering, a simple page load involves far more engineering than most users ever see.',
    date: '03-03-2026',
    img: 'assets/4.jpg',
    author: 'Oliver Hayes',
  },
  {
    id: 5,
    title: 'Learning to Think Like a Software Engineer',
    desc: 'Programming is only part of software engineering. Problem solving, communication, debugging, trade-offs, and understanding systems are equally important.',
    date: '21-03-2026',
    img: 'assets/5.jpg',
    author: 'Nathan Reed',
  },
  {
    id: 6,
    title: 'APIs: The Language That Connects Modern Applications',
    desc: 'A well-designed API creates a clear boundary between systems and allows different applications to evolve without becoming tightly coupled.',
    date: '09-04-2026',
    img: 'assets/6.jpg',
    author: 'Lucas Morgan',
  },
  {
    id: 7,
    title: 'From Database Tables to Real Applications',
    desc: 'A database is more than a place to store information. The way data is modeled directly influences application behavior, performance, and maintainability.',
    date: '26-04-2026',
    img: 'assets/7.jpg',
    author: 'Adrian Foster',
  },
  {
    id: 8,
    title: 'The Hidden Engineering Behind Authentication',
    desc: 'Logging into an application looks simple from the outside, but authentication involves identity, credentials, sessions, tokens, security, and careful backend design.',
    date: '15-05-2026',
    img: 'assets/8.jpg',
    author: 'Ryan Mitchell',
  },
  {
    id: 9,
    title: 'Why Debugging Is One of the Most Valuable Developer Skills',
    desc: 'Bugs are inevitable. The real difference comes from knowing how to isolate a problem, form useful hypotheses, and systematically find its root cause.',
    date: '02-06-2026',
    img: 'assets/9.jpg',
    author: 'Julian Parker',
  },
  {
    id: 10,
    title: 'Building for Users Instead of Just Building Features',
    desc: 'A technically impressive application can still fail if it does not solve a real problem. Great products balance engineering quality with the needs of their users.',
    date: '19-06-2026',
    img: 'assets/10.jpg',
    author: 'Alexander Wright',
  },
];

